# Generated by Django 5.1.2 on 2026-04-30 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_invoice_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='discount',
        ),
    ]
