# Generated by Django 5.1.2 on 2026-05-07 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_invoice_total_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('movement', 'حركة مخزن'), ('invoice', 'فاتورة بيع')], max_length=20, verbose_name='نوع المستند')),
                ('installment_number', models.PositiveIntegerField(verbose_name='رقم الدفعة')),
                ('due_date', models.DateField(verbose_name='موعد الدفع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المستحق')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ المدفوع')),
                ('status', models.CharField(choices=[('pending', 'لم يُسدَّد'), ('partial', 'مسدد جزئياً'), ('paid', 'مسدد بالكامل')], default='pending', max_length=10, verbose_name='الحالة')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='تم إرسال التذكير')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedules', to='store.invoice', verbose_name='الفاتورة')),
                ('movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedules', to='store.stockmovement', verbose_name='حركة المخزن')),
            ],
            options={
                'verbose_name': 'موعد دفعة',
                'verbose_name_plural': 'مواعيد الدفعات الآجلة',
                'ordering': ['due_date'],
            },
        ),
    ]
