# Generated by Django 5.1.2 on 2026-05-09 13:16

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_paymentschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الباكدج / الكوليكشن')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الباكدج')),
                ('main_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[800, 1000], upload_to='collections/', verbose_name='صورة الباكدج')),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر البيع للباكدج (في العرض)')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='التكلفة الفعلية للباكدج (لحساب صافي الربح)')),
                ('is_active', models.BooleanField(default=True, verbose_name='متاح للبيع؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'باكدج / كوليكشن',
                'verbose_name_plural': 'الباكدجات والكوليكشنز',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='المنتج')),
                ('product_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.productsize', verbose_name='المقاس')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.productvariant', verbose_name='اللون')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.productcollection')),
            ],
            options={
                'verbose_name': 'منتج داخل الباكدج',
                'verbose_name_plural': 'المنتجات داخل الباكدج',
            },
        ),
    ]
