# Generated by Django 5.1.2 on 2026-05-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_productcollection_collectionitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='productvariant',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='الترتيب'),
        ),
    ]
