# Generated by Django 5.1.2 on 2026-05-21 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_productvariant_options_productvariant_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={},
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='position',
        ),
    ]
